// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzuyumrczyswbfcunpfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6dXl1bXJjenlzd2JmY3VucGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzYyODMsImV4cCI6MjA1OTYxMjI4M30.6N4hAIDWhp6Fmn4VKuPA8UzluOCW0YTjit23UUTNH6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);